(ns request-flow.http-status)

(def ^:const Ok 200)
(def ^:const Created 201)
(def ^:const NoContent 204)
(def ^:const Found 302)
(def ^:const SeeOther 303)
(def ^:const Malformed 400)
(def ^:const Unauthorized 401)
(def ^:const Forbidden 403)
(def ^:const NotFound 404)
(def ^:const MethodNotAllowed 405)
(def ^:const NotAcceptable 406)
(def ^:const Conflict 409)
(def ^:const UnsupportedMediaType 415)
(def ^:const LoginExpired 440)
(def ^:const InternalServerError 500)
(def ^:const NotImplemented 501)
